server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: stock-ms
  data:
    mongodb:
      uri: mongodb://stock_db:password@localhost:27017/stock_db?authSource=admin
      database: stock_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    config:
      fail-fast: true
    stream:
      bindings:
        toCatalogService-out-0:
          destination: updateCatalog
          content-type: application/json
      rabbit:
        bindings:
          toCatalogService-out-0:
            producer:
              transacted: true
              exchange-type: direct
logging:
  level:
    com.coffeehub: DEBUG